Unity: Fix compile error when build
Assets/Tools/Scripts/EffectEvla2.cs(5,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
Assets/Tools/Scripts/GetParticleEffectData.cs(4,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
Assets/Tools/Scripts/ParticleEffectScript.cs(5,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
Assets/Tools/Scripts/ParticleEffectScript.cs(6,7): error CS0246: The type or namespace name `UnityEditorInternal' could not be found. Are you missing an assembly reference?
Assets/Tools/Scripts/SingleEffectEvla.cs(3,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?